logging:
  config: classpath:logback-prod.xml

spring:
  servlet:
    multipart:
      #临时文件路径
      location: D:\tmp\tmp-datas
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xingyun?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
  #redis配置
  redis:
    #地址
    host: 127.0.0.1
    #端口，默认为6379
    port: 6379
    #数据库
    database: 0
    #密码
    password: password
    #连接超时时间
    timeout: 10s
    lettuce:
      pool:
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池的最大数据库连接数
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
